# Generated by Django 2.1.15 on 2020-06-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='boolean',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
