# Generated by Django 2.1.15 on 2020-06-15 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_boolean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='boolean',
        ),
    ]
